### ISSUE TITLE
Disable dart grammar 

### ISSUE THREAD

**Issue by navidshad** [sublimelsp/LSP-Dart#4]
Hi I want to disable these options but doesn't work, please let me know what shall I do.

```json
// Settings in here override those in "LSP-Dart/LSP-Dart.sublime-settings"
{
	"settings": {
		"missing_default_value": false,
		"missing_default_value_for_parameter": false,
	}
}
```

**Comment by rwols** [comment]
The Dart Analysis Server is tightly linked with the SDK in general. Have you tried writing an analysis_options.yaml file? https://dart.dev/guides/language/analysis-options
