### ISSUE TITLE
Issue with latest Flutter/Dart version. Not finding SDK

### ISSUE THREAD

**Issue by sollymay** [sublimelsp/LSP-Dart#6]
Seems like there is an issue with the latest Flutter/Dart version, in which the dart executable is not being found. (On Linux)

Getting the following error:
![Screenshot from 2021-09-07 15-45-59](https://user-images.githubusercontent.com/6496698/132402360-56d2a349-54f6-436e-8cf4-6dceb4097b10.png)
Even though I'm pointing to the right place in LSP-Dart Settings

![Screenshot from 2021-09-07 15-47-07](https://user-images.githubusercontent.com/6496698/132402384-e91aad0d-be22-411f-8b8b-9e541d269af4.png)

Even after removing the env setting, getting an error with the automatic finding.

I made sure I have both flutter and dart on my path:

![Screenshot from 2021-09-07 15-49-22](https://user-images.githubusercontent.com/6496698/132402550-a8d30692-38e3-4423-9207-2a7ba9386aad.png)

**Comment by rwols** [comment]
The language configuration provided by this package is called “Dart”, but the error message mentions “dart” (lowercase). Do you have such a configuration present in Packages/User/LSP.sublime-settings? If so remove it.

**Comment by sollymay** [comment]
Lol, feel stupid :smile: 

Forgot I had that cause on MacOS I don't have to do any of this config :smile: 

Closing
