### ISSUE TITLE
Can one disable the new **INLAY HINT** (inferred types, parameters...)?

### ISSUE THREAD

**Issue by Alexandre03zxc** [sublimelsp/LSP-Dart#8]
Hi, I like the support. It's working really well. Though after updating the plugin, I step upon this new feature (which I think come from dartlang lsp). It's a great addition, but it causing me some problems.

Cause:
- I used to work without it. Now the code looks so different and with longer line length
- Precision problems while navigating/selecting with cursor or arrow keys.

![example_0fn39a3w](https://github.com/sublimelsp/LSP-Dart/assets/37878481/364df1b2-25b4-49a5-bd9d-93478a3cfe34)

Overall I prefer to work without this feature (if possible).

- Is it a linter option that one can disable in "analysis_options.yaml" file ?
- Do "Dart.closing_labels" (plugin.py) controls these inlay hints too ?

**Comment by rwols** [comment]
Do you have a screenshot of the hints you want disabled?

It could also be the setting "show_inlay_hints" in LSP.sublime-settings (see: "Preferences: LSP Settings" from the command palette), though it's set to `"false"` by default.

**Comment by Alexandre03zxc** [comment]
Thank you.
It was "show_inlay_hints". I don't know how I missed that (or when I get it activated).
