### ISSUE TITLE
Keeps failing

### ISSUE THREAD

**Issue by ChuksFestus** [sublimelsp/LSP-Dart#9]
I've never been able to successfully start it since installation. it keeps throwing this error 
<img width="445" alt="Screenshot 2024-01-04 at 12 25 42 AM" src="https://github.com/sublimelsp/LSP-Dart/assets/13522877/bbf9c61b-cd42-4ba0-977b-7645d87fc33d">

Here's my settings
<img width="746" alt="Screenshot 2024-01-04 at 12 26 50 AM" src="https://github.com/sublimelsp/LSP-Dart/assets/13522877/ff665f1f-66e6-4f7c-854d-a56e93f0f0bb">

**Comment by whck6** [comment]
+1

**Comment by rwols** [comment]
The FLUTTER_ROOT is supposed to point to the root of the SDK. In your, case:

```js
"env": {
    "FLUTTER_ROOT": "/Users/DEV-CHUKS/dev/tools/flutter
}
```

There should be no need to define `DART_SDK` if `FLUTTER_ROOT` is defined.

The VSCode extension looks for the same kind of environment variable: https://dartcode.org/docs/settings/#dartfluttersdkpath

**Comment by whck6** [comment]
Without any settings after via brew install flutter.

**Comment by rchl** [comment]
Seems like this is resolve. Nothing more to do here?
